# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 04f1b0eeec4b6c8f1e83a45d7159cc4961fd135b707a3b54621539fbbca4803e669a4101843dd968cac5e108249885bb0bc3fb45dffc135e2d75306a61e25ed9

test:
  secret_key_base: 00f9de3f3283cab7be4a2792cd8cfb79166abc8c24f1294a8fa3d8fbe12d1d749a464bd5352fce295cee497e5e8692f4b3d3e066f980d3f8d2f9250d559dd0be

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
